### ISSUE TITLE
Service for Openresty/Nginx

### ISSUE THREAD

**Issue by BenMorganIO** [smashedtoatoms/asdf-openresty#1]
Hey there,

Thanks for this amazing plugin!

I've installed this bad boy and I'm wondering if there's a `sudo service nginx start/reload/stop` command anywhere or if I have to set that up myself?

**Comment by smashedtoatoms** [comment]
Nah, it doesn't really have any of the production perks.  It's intended as a dev resource that's bound to the dev environment.  What I do is include it as a dependency in my .tool-versions file, and then start it it with a script using `openresty -c nginx.conf`.  Then I can have a separate config and isolated nginx instance for each app I am working on.

**Comment by smashedtoatoms** [comment]
Sorry about that.  I wrote this plugin and the postgres one so I could isolate them really easily, but the tradeoff is that none of the automated parts are done.  I do it all manually per dev environment.  I should probably write up what I am doing as an example, because I realize that it's pretty annoying outside of my little use case.

**Comment by BenMorganIO** [comment]
Ah KK. I was just using it as a quick setup option on a Raspberry Pi. Thanks :)
